### ISSUE TITLE
Secure Password Storage & Generation

### ISSUE THREAD

**Issue by oliverEddy** [ThierryGibbons/CS205-Password-Manager#4]
This is the core functionality of our application. We need to store user passwords (and other credentials, like user names) securly in a vault. We also need to generate strong unique passwords which will be stored in this vault. 

This task involves developing the backend to securely store password entries and integrating a password generator. 

Acceptance crietra: 

*Leaving blank for further dicussion*

**Comment by ThierryGibbons** [comment]
encrypt passwords using public and private keys
